#theme: jekyll-theme-hacker
#remote_theme: "jekyll/minima@bf9ef98"
remote_theme: daattali/beautiful-jekyll@6.0.1 
title: Josef Adamčík - Resume
description: 
markdown: GFM
minima:
  hide_site_feed_link: true
